### ISSUE TITLE
Runtime Error on InitializeSdk

### ISSUE THREAD

**Issue by fedegont** [oseamiya/AdmobExtension#2]
Hi!

Found this error this morning..

![admobextension](https://user-images.githubusercontent.com/30378580/168443711-28c18307-b1d1-4153-bd69-413450e03af9.jpg)

UPDATE: Oops. I see. Only in Companion it doesn't work. As explained before. Sorry.

**Comment by oseamiya** [comment]
Yes, the extension don't work in companion app. Because companion app don't have the required manifest.
